# Generated by Django 5.1.5 on 2025-01-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('farmer', 'Farmer'), ('manager', 'Manager')], max_length=10, null=True),
        ),
    ]
