# Generated by Django 5.1.4 on 2025-02-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_farmer_total_payments_customuser_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='farmer',
            name='phone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
