# Generated by Django 5.1.4 on 2025-02-09 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_farmer_phone_number_farmer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='user',
        ),
    ]
