# Generated by Django 5.1.4 on 2025-02-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_harvestuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestuser',
            name='label',
            field=models.CharField(default='Tea', max_length=100),
        ),
    ]
