# Generated by Django 5.1.5 on 2025-01-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_stk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mpesaresponse',
            old_name='checkout_request_id',
            new_name='chechout_request_id',
        ),
        migrations.AlterField(
            model_name='mpesaresponse',
            name='customer_message',
            field=models.CharField(max_length=15),
        ),
    ]
