# Generated by Django 5.1.5 on 2025-02-13 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_stk', '0002_rename_checkout_request_id_mpesaresponse_chechout_request_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mpesaresponse',
            old_name='chechout_request_id',
            new_name='checkout_request_id',
        ),
    ]
