# Generated by Django 5.1.5 on 2025-02-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_stk', '0003_rename_chechout_request_id_mpesaresponse_checkout_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesarequest',
            name='phone_number',
            field=models.CharField(max_length=17),
        ),
    ]
