# Generated by Django 5.1.5 on 2025-02-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_stk', '0004_alter_mpesarequest_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesarequest',
            name='phone_number',
            field=models.CharField(max_length=18),
        ),
    ]
