# Generated by Django 5.1.5 on 2025-02-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_stk', '0005_alter_mpesarequest_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesaresponse',
            name='customer_message',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='mpesaresponse',
            name='response_description',
            field=models.CharField(),
        ),
    ]
